### ISSUE TITLE
installation dependencies issue

### ISSUE THREAD

**Issue by shu251** [MikkoVihtakari/ggOceanMaps#12]
Hello,
I've run into an issue when installing dependencies for "ggOceanMaps". Following this message:
```
also installing the dependencies ‘rgdal’, ‘rosm’, ‘terra’, ‘lwgeom’, ‘ggspatial’, ‘raster’, ‘sf’, ‘rgeos’, ‘stars’, ‘smoothr’, ‘units'
```
I get error messages of configuration failed for each package, leaving with 'had nonzero exit' status.

Any suggestions for installation? I've tried various versions of installing from CRAN and GitHub with ```dependencies = TRUE```. Upon trying to install listed packages separately, ran into many issues with the ggspatial package, which I also tried install in a variety of ways. 
Any advice would be helpful!

**Comment by MikkoVihtakari** [comment]
Yes, this can be a bit difficult. I have lately struggled with terra even though ggOceanMaps does not make a dependency to that package.

Try installing the packages that throw errors manually (`install.packages("rgdal")`). Some will go without problems, while rgdal, terra, ggspatial, sf or stars may not work. If that is the case, check the version of gdal and proj you have installed. Those have to be >= 3 and >= 6, respectively.

Google will help you finding out how to do all that I write above.

Let me know if this solved the issue.

**Comment by MikkoVihtakari** [comment]
No answer. I'll close, open if needed
