### ISSUE TITLE
Currents 

### ISSUE THREAD

**Issue by NicoSchiff** [MikkoVihtakari/ggOceanMaps#14]
Hi,

Do you intend to add the current=TRUE option as was the case in the PlotSvalbard package?
I am a bit new and would like to know how I could include pie charts (also like in the PlotSvalbard package).

Thanks 

Nicolas

**Comment by MikkoVihtakari** [comment]
Including ocean currents for the entire world would be time consuming and difficult to do right for all various user-cases. Better that the user adds the currents they want using ggplot syntax. See here: https://aen-r-workshop.github.io/4-ggOceanMaps/ggOceanMaps_workshop.html#50

The same applies for pie-charts. You can add them as you would add them to any ggplot. See here for instance: https://stackoverflow.com/questions/10368180/plotting-pie-graphs-on-map-in-ggplot

**Comment by MikkoVihtakari** [comment]
Did the above help?

**Comment by MikkoVihtakari** [comment]
No answer. Closing. Open if needed.

**Comment by NicoSchiff** [comment]
Hello, I am very sorry for my very late reply. Thank you very much, it fits perfectly with what I want to do! 

Once again, sorry
