### ISSUE TITLE
Adding Latitude and longitude labels to polar map

### ISSUE THREAD

**Issue by jzehnpfennig** [MikkoVihtakari/ggOceanMaps#17]
Hello, 

I am trying to create a map of Antarctica and it works with the code: basemap(limits = c(-180, 180, -70, -60). However I would like to add labels to the latitude and longitude lines in the map, and I am struggling to figure out how. 

Any suggestions? 

Thank you!

**Comment by MikkoVihtakari** [comment]
Yes, this feature was included in PlotSvalbard but I have not gotten to add it to ggOceanMaps as I have not needed it yet. Parts of the required code are there though. See here for how the [grid is created in PlotSvalbard](https://github.com/MikkoVihtakari/PlotSvalbard/blob/7db5ae3abea50598938c4dd83648c4850c3cdb6e/R/basemap_data.R#L88) and here how [it would be used in ggOceanMaps](https://github.com/MikkoVihtakari/ggOceanMaps/blob/7d5ace5cc852515d91a198f2231cbab060f101f8/R/map_cmd.R#L98). 

Perhaps you can manage to make what you need from these snippets?

**Comment by renliang1996** [comment]
Hello,

This feature is very useful, but your code snippet is very troublesome to use. Could you update it?

**Comment by MikkoVihtakari** [comment]
> This feature is very useful, but your code snippet is very troublesome to use. Could you update it?

Troublesome in what way? I still get the same figure than above except that the land does not get dissolved correctly. A solution to that has been shown [here](https://mikkovihtakari.github.io/ggOceanMaps/articles/ggOceanMaps.html#known-issues).
