### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [MikkoVihtakari/ggOceanMaps#18]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

Maybe related to #5

**Comment by MikkoVihtakari** [comment]
Thanks Roger. Will do so. When the `rosm` package dependencies are fixed, detaching rgdal should be straight forward.

Related to this: https://github.com/paleolimbot/ggspatial/issues/110

**Comment by rsbivand** [comment]
Does this mean that the use of **rgeos** in `rgeos::createSPComment` (fixed by https://github.com/r-spatial/sf/pull/2069), `rgeos::gDistance` `rgeos::gIntersection` `rgeos::gIsValid` `rgeos::gSimplify` in code is also removed? I don't see **rgeos** being removed from `NAMESPACE`, even in the `sf-version` branch. If need be, use `sf_use_s2(FALSE)` to emulate **rgeos**.

**Comment by MikkoVihtakari** [comment]
Yes, I forgot rgeos. I'd need to rewrite many functions. Fixing that has to wait some time.

**Comment by MikkoVihtakari** [comment]
Thanks, will fix before October.

**Comment by rsbivand** [comment]
Thanks! If you can manage June (when we switch `sp` from using `rgdal` to using `sf` internally, evolution status 2), that would be helpful, as we are unsure what that may lead to when packages interact.

**Comment by rsbivand** [comment]
Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023.

**Comment by rsbivand** [comment]
You may safely leave sp and raster, only rgdal, rgeos and maptools are retiring. https://r-spatial.org/r/2023/04/10/evolution3.html has lots of hints on work-arounds.

**Comment by MikkoVihtakari** [comment]
Should be done now: https://github.com/mikkovihtakari/ggoceanmaps/tree/sf-version

It goes to CRAN once I have controlled that everything works.

**Comment by MikkoVihtakari** [comment]
@rsbivand, any idea why ggOceanMaps still imports sp, raster and rgeos even though these are not mentioned anywhere in [DESCRIPTION](https://github.com/MikkoVihtakari/ggOceanMaps/blob/sf-version/DESCRIPTION) nor [NAMESPACE](https://github.com/MikkoVihtakari/ggOceanMaps/blob/sf-version/NAMESPACE)?

``` r
library(ggOceanMaps)
#> Loading required package: ggplot2
#> ggOceanMaps: Setting data download folder to a temporary folder
#> /var/folders/9v/b70pd53x04d3jjmlrbcgp4_w0000gv/T//RtmpcEjorI. This
#> means that any downloaded map data need to be downloaded again when you
#> restart R. To avoid this problem, change the default path to a
#> permanent folder on your computer. Add following lines to your
#> .Rprofile file: {.ggOceanMapsenv <- new.env(); .ggOceanMapsenv$datapath
#> <- 'YourCustomPath'}. You can use usethis::edit_r_profile() to edit the
#> file.'~/Documents/ggOceanMapsLargeData'would make it in a writable
#> folder on most operating systems.

pack <- available.packages()
pack["ggOceanMaps","Imports"]
#> [1] "sp, raster, sf, rgeos, methods, utils, stars, smoothr, units,\ndplyr, parallel"
```

<sup>Created on 2023-07-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by rsbivand** [comment]
`available.packages` looks at the package on CRAN, not the locally installed package. `2.0.0` arrived earlier today, but all the CRAN checks https://cran.r-project.org/web/checks/check_results_ggOceanMaps.html are for the previous version, as is:
```
> pack["ggOceanMaps", c("Version", "Depends", "Imports")]
                                                                         Version 
                                                                         "1.3.4" 
                                                                         Depends 
                                              "R (>= 3.5.0), ggplot2, ggspatial" 
                                                                         Imports 
"sp, raster, sf, rgeos, methods, utils, stars, smoothr, units,\ndplyr, parallel" 
```

**Comment by rsbivand** [comment]
Yes, just 206 packages left to help ... thanks for your help!
