### ISSUE TITLE
Esoteric projections with 'raster_bathymetry()'

### ISSUE THREAD

**Issue by robwschlegel** [MikkoVihtakari/ggOceanMaps#2]
Hello Mikko,
Firstly, what a fantastic package! Thank you for this contribution to the community. I recently started work for one of the EU Horizon2020 Arctic projects (FACE-IT), and __`ggOceanMaps`__ has been immensely helpful in easily and tidily plotting maps for study sites in the Arctic.

I have however encountered an issue I was hoping you could advise with, even though it falls a bit outside of the purview of the package. In your tutorial on how to use [custom shapefiles](https://mikkovihtakari.github.io/ggOceanMaps/articles/ggOceanMaps.html) you recommend the use of higher resolution bathymetry products. But the [IBCAO](https://www.gebco.net/data_and_products/gridded_bathymetry_data/arctic_ocean/) product (also produced by GEBCO) is an Arctic bathymetry product that is perhaps higher resolution than [GEBCO](https://www.gebco.net/data_and_products/gridded_bathymetry_data/). IBCAO is on a 200m square grid, rather than the GEBCO 15 arc second grid, so will have slightly better resolution at lower latitudes. The real benefit is that this product is meant to be more focussed on the quality of the Arctic data specifically, than the global GEBCO product may be.

The issue specifically is that with the IBCAO product I can't determine what the correct projection is that it wants. When using `raster_bathymetry()` to automagically prepare the bathy data, it falls over on this line as it is not able to use the default projection `ras <- raster::projectRaster(from = ras, crs = sp::CRS(proj.out))`. If I provide it with the global projection "+init=epsg:4326" the function runs, but provides an empty result. According to the IBCAO website the projection for the product is Polar Stereographic projection co-ordinates (meters). So I followed the [projection website](http://epsg.io/) from your tutorial and searched for Polar Stereographic, which led to [EPSG:3995](http://epsg.io/3995), but this doesn't work either. Are you able to advise on how to get this IBCAO product to work with __`ggOceanMaps`__?

Thank you,
-Robert

**Comment by MikkoVihtakari** [comment]
Thank you, Robert, and my apologies for answering late. I seem not to receive notifications even though I am watching this repository...

As for your question, I have not played around with IBCAO data but what you try to do, makes sense. The projection should be EPSG:3995 or EPSG:3996. You should be able to see this by opening the file using the `raster` package. Once you have the file open, you can just debug through `raster_bathymetry()` line by line and see where it fails exactly. I suppose the conversion from EPSG:3995 to EPSG:3995 somewhere along the loop may be a bad idea :D

I, unfortunately, do not have time to look into this at the moment, but will check it later when I have time. If you already solved the issue, posting the solution here would be appreciated so I could add it to the user manual.

**Comment by robwschlegel** [comment]
Hello Mikko,
I haven't solved the issue yet either. I've stepped away from this issue as the GEBCO bathymetry data are generally fine. If I do return to this and find the solution I'll post it here. I did go through the function line by line back in January and recall that it was a raster package function that was actually the issue, not your functions use of it. Some sort of raster bug, but that was a several weeks ago and I can't remember the details.
All the best,
-Robert

**Comment by MikkoVihtakari** [comment]
Thanks Robert. Let's keep this issue open to remind us that we should check it out once we find time ;)

**Comment by robwschlegel** [comment]
Hello Mikko,
Thank you for looking into this. Unfortunately on my machine this does not run. Regardless of which arguments are or are not provided to both `proj.bathy` and proj.out`, the same error occurs: "Error in CRS(x) : no arguments in initialization list". I downloaded the most recent version of `ggOceanMaps` from this GitHub repo. And I ensured that my version of the IBCAO NetCDF file is not corrupt.  It appears as though somewhere in the `raster_bathymetry` function the CRS values are not being assigned correctly. After googling the error it appears as though this could be an issue locally on my machine. I wasn't able to resolve it in a reasonable amount of time though, so am not certain. If I do find the fix for this in the future I will post it here.
All the best,
-Robert

p.s. my sessionInfo:

R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=fr_FR.UTF-8   
 [6] LC_MESSAGES=en_GB.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggOceanMaps_1.1.9 ggspatial_1.1.5   ggplot2_3.3.3    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6         pillar_1.6.1       compiler_4.1.0     class_7.3-19       tools_4.1.0        ncdf4_1.17         lattice_0.20-44   
 [8] lifecycle_1.0.0    tibble_3.1.2       gtable_0.3.0       pkgconfig_2.0.3    rlang_0.4.11       DBI_1.1.1          rgdal_1.5-23      
[15] parallel_4.1.0     xfun_0.23          e1071_1.7-7        withr_2.4.2        dplyr_1.0.6        raster_3.4-10      rgeos_0.5-5       
[22] generics_0.1.0     vctrs_0.3.8        classInt_0.4-3     grid_4.1.0         tidyselect_1.1.1   glue_1.4.2         sf_0.9-8          
[29] R6_2.5.0           fansi_0.5.0        sp_1.4-5           purrr_0.3.4        magrittr_2.0.1     codetools_0.2-18   scales_1.1.1      
[36] ellipsis_0.3.2     units_0.7-1        assertthat_0.2.1   colorspace_2.0-1   utf8_1.2.1         tinytex_0.32       KernSmooth_2.23-20
[43] proxy_0.4-25       munsell_0.5.0      crayon_1.4.1

**Comment by MikkoVihtakari** [comment]
Hmm...that is weird indeed. Especially because the current Github version passes R CMD CHECK on Ubuntu: https://github.com/MikkoVihtakari/ggOceanMaps/runs/2715617955

Try deleting ggOceanMapsData, ggOceanMapsLargeData, and install those again.

**Comment by MikkoVihtakari** [comment]
Also, please tell me to which GEOS version `sf` and `rgeos` link to?

On my machine:

``` r
library(sf)
#> Linking to GEOS 3.8.1, GDAL 3.2.1, PROJ 7.2.1
library(rgeos)
#> Loading required package: sp
#> rgeos version: 0.5-7, (SVN revision (unknown))
#>  GEOS runtime version: 3.9.1-CAPI-1.14.2 
#>  GEOS using OverlayNG
#>  Linking to sp version: 1.4-5 
#>  Polygon checking: TRUE
```

<sup>Created on 2021-06-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by robwschlegel** [comment]
library(sf)
Linking to GEOS 3.6.2, GDAL 2.2.3, PROJ 4.9.3

library(rgeos)
Loading required package: sp
rgeos version: 0.5-5, (SVN revision 640)
 GEOS runtime version: 3.6.2-CAPI-1.10.2 
 Linking to sp version: 1.4-5 
 Polygon checking: TRUE 

So it looks like almost all of my libraries are out of date. Which is odd considering that I have run `sudo apt-get update` before I responded earlier today. Perhaps I need to be accessing different distributions by adding other PPA keys to my software libraries. I'll have a look at getting GEOS, GDAL, and PROJ updated and see if that sorts out the issue. RStudio also recently started crashing whenever any plots are visualised. So some recent update somewhere on my computer has been causing a whole range of exciting problems. I'll get back to you later today

**Comment by MikkoVihtakari** [comment]
Yes, try and update those libraries. Maybe it has something to do with that (remember that they were changed from PROJ4 to PROJ6 last year). You'll find instructions how to do that by googling (update geos linux).

Then update ggOceanMapsData. It's PROJ6 now. 

I think your problem is related to the shift. Something is not up to date.

**Comment by robwschlegel** [comment]
I've updated my geospatial libraries and that solved the issue. For anyone on the internet that finds this post, I used the code provided here to update my libraries: https://nowosad.github.io/whyr_webinar004/#36
I did need to add a new PPA key to my list because the one I had was not allowing me to update to the newer necessary versions.

Note however that running `raster_bathymetry` does still provide the following message: "bathy does not contain coordinate reference information. Using EPSG:3996. Adjust this setting by changing the proj.bathy argument"
Which I think is odd because one is already explicitly specifying which projection to use in the `proj.bathy` argument.

**Comment by MikkoVihtakari** [comment]
Good to hear that it solved the issue. That message is just one I wrote. It is because the bathymetry grid you downloaded actually does not contain CRS (that was the original problem in this thread) and one has to guess it by defining `proj.bathy`.

Is that message confusing? How should I change it?

Also, that reminds me that I should add `verbose` argument to that function and `verbose = FALSE` would eliminate such messages.

**Comment by robwschlegel** [comment]
`verbose = FALSE` is a good way to handle it.
If it's not too much work. I would reorder the projection message so that it only appears if the `bathy` object doesn't have a `CRS` _and_ the user hasn't specified a projection with `proj.bathy`. The way it is now it makes me unsure if the function is acknowledging the projection I am providing to `proj.bathy`. I think it is good that `raster_bathymetry` guesses at the projection to use so I wouldn't change that.

**Comment by MikkoVihtakari** [comment]
It only happens when `bathy` has no projection but there is no way separating user input as long as `proj.bathy = "EPSG:4326"` is the default. If I left it blank, the function would throw an error every time one tries to read a raster without projection (most, if not all, of them).

**Comment by MikkoVihtakari** [comment]
Or one could do something like `if(missing(proj.bathy)) proj.bathy <- "EPSG:4326"` to separate user input and throw the message. Anyway, then it would not be obvious from the Usage field.

**Comment by robwschlegel** [comment]
Sounds like a plan :)

**Comment by MikkoVihtakari** [comment]
Thanks for the feedback. Implemented here: https://github.com/MikkoVihtakari/ggOceanMaps/commit/6bdc3d279c4e0690daf2f47db5390872cbd64dbf

**Comment by robwschlegel** [comment]
NIce!
