### ISSUE TITLE
 Plotting extent changed by reorder_layers function 

### ISSUE THREAD

**Issue by mkmor** [MikkoVihtakari/ggOceanMaps#21]
I would like to plot the `basemap` land layers on top of my vector polygon layers in `ggplot`, but I think there is a bug in the function that I hope can be worked out. 

```
library(ggOceanMaps)

p = basemap(limits=c(-92, -47, 40, 79),
        projection.grid = TRUE, grid.col=NA, rotate=T,
        land.border.col = "darkgrey", land.col = "lightgrey")

p
```
![original_map](https://user-images.githubusercontent.com/64548463/228389011-17c0d47d-c0e2-4f10-b7bd-54f65f571aad.png)

```
reorder_layers(p)
```
![reorder_layers](https://user-images.githubusercontent.com/64548463/228389026-fba4e8a0-0e91-42f2-9e1e-bbe2221d6fff.png)

When I run the `reorder_layers()` function, the plotting extent becomes centered over the prime meridian rather than remaining as the specified extent in the original map variable. It looks like it might have to do with the CRS projection perhaps, as the lat/long units are different in the second map.

I haven't included any of the vector layers because the same thing happens when I am only plotting the base map. Any ideas how this can be fixed?

**Comment by MikkoVihtakari** [comment]
Fixed with this: https://github.com/MikkoVihtakari/ggOceanMaps/commit/012894cb0863ec5e73339ca8ccc7633e3f0dd6e0

At the moment of writing, install from a separate developmental branch: https://github.com/mikkovihtakari/ggoceanmaps/tree/sf-version (This branch will be made master and uploaded to CRAN once the conversion is complete).

``` r
library(ggOceanMaps)
#> Loading required package: ggplot2
#> ggOceanMaps: Setting data download folder to a temporary folder
#> /var/folders/9v/b70pd53x04d3jjmlrbcgp4_w0000gv/T//RtmpEDia7L. This
#> means that any downloaded map data need to be downloaded again when you
#> restart R. To avoid this problem, change the default path to a
#> permanent folder on your computer. Add following lines to your
#> .Rprofile file: {.ggOceanMapsenv <- new.env(); .ggOceanMapsenv$datapath
#> <- 'YourCustomPath'}. You can use usethis::edit_r_profile() to edit the
#> file.'~/Documents/ggOceanMapsLargeData'would make it in a writable
#> folder on most operating systems.
packageVersion("ggOceanMaps")
#> [1] '1.4.0'

p = basemap(limits=c(-92, -47, 40, 79), rotate=T)

p
```

![](https://i.imgur.com/kWRLznt.png)

``` r

reorder_layers(p)
```

![](https://i.imgur.com/jM8wjW6.png)

<sup>Created on 2023-06-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
