### ISSUE TITLE
Unable to install ggOceanMapsData

### ISSUE THREAD

**Issue by tsippel10** [MikkoVihtakari/ggOceanMaps#22]
I'm unable to install ggOceanMaps data using either of the suggested commands;

devtools::install_github("MikkoVihtakari/ggOceanMapsData")

or

install.packages(
  "ggOceanMapsData", 
  repos = "https://cloud.r-project.org")

Here is my R info

> sessionInfo()
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggOceanMaps_1.3.4 ggspatial_1.1.7   ggplot2_3.4.2

**Comment by MikkoVihtakari** [comment]
Could you tell what kind of error `remotes::install_github("MikkoVihtakari/ggOceanMapsData")` throws at you?

**Comment by Phoebe-AA** [comment]
I was having a similar problem but the remotes::install_github.... worked nicely for me. Thanks!

**Comment by MikkoVihtakari** [comment]
Then it's a problem installing the remotes package rather than a problem with ggOceanMaps. I'll change the instruction to remotes.

**Comment by tsippel10** [comment]
Sorry the slow reply, I didn’t notice your response until now. Here is the
error message I get.


remotes::install_github("MikkoVihtakari/ggOceanMapsData")

Downloading GitHub repo ***@***.***

Error in utils::download.file(url, path, method = method, quiet = quiet,  :

  cannot open URL '
https://api.github.com/repos/MikkoVihtakari/ggOceanMapsData/tarball/HEAD'

I’m using remotes_2.4.2

Thanks,

Tim

**Comment by MikkoVihtakari** [comment]
Can you install other packages with `remotes::install_github`?

**Comment by tsippel10** [comment]
Good question. I’m getting similar errors from using remotes to install 2
other packages. Any idea what this is about?

FYI, I’ve also tried to install ggOceanMapsData the .zip file I downloaded
from your website. That didn’t work either.

> remotes::install_github("r-spatial/mapview")

Downloading GitHub repo ***@***.***

Error in utils::download.file(url, path, method = method, quiet = quiet,  :

  cannot open URL '
https://api.github.com/repos/r-spatial/mapview/tarball/HEAD'



> remotes::install_github("riatelab/cartography")

Downloading GitHub repo ***@***.***

Error in utils::download.file(url, path, method = method, quiet = quiet,  :

  cannot open URL '
https://api.github.com/repos/riatelab/cartography/tarball/HEAD'

**Comment by MikkoVihtakari** [comment]
Seems like a connection problem or something. Try if googling helps. If not, perhaps open an issue on the `remotes` Github site. You may link this one.
