### ISSUE TITLE
Error in UseMethod("st_transform") 

### ISSUE THREAD

**Issue by yiyuanbi** [MikkoVihtakari/ggOceanMaps#29]
I just got error when I use ggOceanMaps version 2.1.1 in the Rstudio server.

Error in UseMethod("st_transform"): 
  "st_transform" has no methods applicable to the target object "c('SpatialPolygonsDataFrame', 'SpatialPolygons', 'Spatial')"

Could you let me know how to fix it?

**Comment by MikkoVihtakari** [comment]
Can't be sure based on this little diagnostic, but it seems that there is an sp object lingering somewhere. Try deleting the content of your ggOceanMapsLargeData folder if you use one. Also make sure to remove the ggOceanMapsData package. It is not needed any longer.

**Comment by MikkoVihtakari** [comment]
No answer. I assume this is solved. Reopen if not.
