### ISSUE TITLE
Issues with next ggplot2 version

### ISSUE THREAD

**Issue by thomasp85** [MikkoVihtakari/ggOceanMaps#3]
Hi

We are preparing a new ggplot2 release and our tests have shown that ggOceanMaps has some issues with it. It is specifically related to a change in how non-sf layers behave when mixed with sf layers. Before, any non-sf layer was considered to be encoded in whatever CRS the coordinate system used, whereas it now is considered to be encoded in `sf::st_crs(4326)` (i.e. latitude and longitude values). To get the old behaviour set `default_crs = NULL` in `coord_sf()`.

We plan to submit the next version of ggplot2 on May 31st

best
Thomas

**Comment by MikkoVihtakari** [comment]
Hi Thomas,

Thank you for the information. I am currently updating the CRS system to PROJ6. Can make sure that the package cooperates with changes to ggplot2 while I am at it. Is the version you plan to submit the most recent GitHub version? I.e. can I do the debugging with it and trust that it wont behave differently to the May 31st CRAN version?

All the best,
-Mikko

**Comment by thomasp85** [comment]
The release version lives in the v3.3.4-rc branch

**Comment by MikkoVihtakari** [comment]
Thanks. Also, do you have thoughts how to ensure backwards compatibility in ggOceanMaps?

**Comment by thomasp85** [comment]
it is not really possible to guard against users not updating ggOceanMaps - to guard against users updating ggOceanMaps but not ggplot2 you can just add a versioned dependency in the DESCRIPTION file (i.e. `Imports: ggplot2 (>= 3.3.4)` — however this would mean that you'd have to wait to submit until after ggplot2 has been updated. This is usually fine though - CRAN won't kick you out the second your package breaks

**Comment by MikkoVihtakari** [comment]
ggOceanMaps will be kicked out 4th of June anyways due to a mystical bug on Solaris I have not managed to solve: https://cran.r-project.org/web/checks/check_results_ggOceanMaps.html

I believe it is related to the PROJ6 shift. I try to change all sp::proj4string to sf::st_crs in hope that both Solaris and new ggplot2 will understand what I mean...

**Comment by thomasp85** [comment]
Ugh - good luck 😕... You can check on solaris with Rhub btw so you don't have to do it completely in the blind

**Comment by MikkoVihtakari** [comment]
Yup, this: https://blog.r-hub.io/2020/05/14/checking-your-r-package-on-solaris/

I did manage to replicate the error message. Now all that remains is to find what causes it...Can't get the error in any other OS I have in use (Fedora, Mac, Windows). It feels unfair that I have to debug for a non-open OS "no one" uses, but that's how it is...

**Comment by thomasp85** [comment]
Preaching to the choir — at least you can replicate it, that is not always the case :-)

**Comment by MikkoVihtakari** [comment]
I added `default_crs = NULL` to all `coord_sf()` functions (not on GitHub yet as it does not work on the current ggplot2 version). A problem is that `coord_sf()` does not contain ..., which makes coord_sf(`default_crs = NULL`) fail on any other version of ggplot2 than your development version. I expect that many other packages and private scripts will have the same problem. Are you certain that you want to implement this planned change this way? Would it not be better to implement it to the `crs` argument for example? You could change it to `NA` in the new versions, which would mean `sf::st_crs(4326)` while the old versions would retain `NULL` and the current behavior, for example...

Sure I can make an if-else statement testing the ggplot2 version in my package, but that will make the code quite complex.

**Comment by MikkoVihtakari** [comment]
It should be fixed now: https://github.com/MikkoVihtakari/ggOceanMaps/commit/81e5e58770e4826ec216e4e54dc56c62860adecb

I added if statements checking for ggplot2 version in `map_cmd`.

Will close. Reopen if needed.
