### ISSUE TITLE
Error in UseMethod("st_transform") for everything

### ISSUE THREAD

**Issue by MiaWege** [MikkoVihtakari/ggOceanMaps#30]
Hello,

I have been using ggOceanMaps for a long time. I tried to run an old map and received the error:

Error in UseMethod("st_transform") : 
  no applicable method for 'st_transform' applied to an object of class "c('SpatialPolygonsDataFrame', 'SpatialPolygons', 'Spatial', 'SpatialVector')"

After fiddling with it trying to find the problem, I went back just to basic basemap from the manual and I still get the error.
library(ggOceanMaps)
library(ggspatial) # for data plotting
basemap(limits = 60) # A synonym: basemap(60)  

Is this related to the order in which I should load packages? I see ggOceanMaps was rewritten to use sf. I have sf installed and loaded.
Thank you

**Comment by MikkoVihtakari** [comment]
Yup, that's the reason. Try updating sf, ggOceanMaps, delete content in ggOceanMapsLargeData and the entire ggOceanMapsData repository. That should solve the issue.

**Comment by MikkoVihtakari** [comment]
I'll close this. Open if the answer did not help.
