### ISSUE TITLE
unused argument (linewidth = grid.size)

### ISSUE THREAD

**Issue by barbarabayer** [MikkoVihtakari/ggOceanMaps#31]
When I try any basemap command, I am getting the following error:

> basemap(limits = c(-20, 20, 40, 59))
Error in element_line(colour = grid.col, linewidth = grid.size) : 
  unused argument (linewidth = grid.size)

**Comment by MikkoVihtakari** [comment]
How old is your ggplot2?

**Comment by barbarabayer** [comment]
I have 3.3.6. That must be the issue. Thanks!
