### ISSUE TITLE
Possible bug when .ggOceanMapsenv$datapath has a '.' in a directory name

### ISSUE THREAD

**Issue by eaalto** [MikkoVihtakari/ggOceanMaps#32]
After calling basemap(), the code runs for a bit, then comes into
basemap_data_define_shapefiles() and calls:
 shapefiles <- shapefile_list(shapefile.name)
Given a DecimalDegree shapefile.name and after processing, this returns a list that starts like this:

$name
[1] "DecimalDegree"
$land
[1] "dd_land"
$bathy
                      vector 
"~/ggOceanMapsData/dd_bathy" 
...

In this case, "bathy" is the .ggOceanMapsEnv$datapath combined with "dd_bathy". This path works fine. But first I had the datapath be: "C:/Users/lime/AppData/Local/R/win-library/4.2/ggOceanMapsData" 

which leads to:
$bathy
                      vector 
"C:/Users/lime/AppData/Local/R/win-library/4.2/ggOceanMapsData/dd_bathy" 
...

Now if we go forward to the function load_map_data(), we reach the following code (numbered locally here):
1 x[c("land", "glacier", "bathy")] <- lapply(x[c("land", "glacier", 
2    "bathy")], function(k) {
3    if (is.null(k)) {
4      NULL
5    }
6    else if (grepl("/", k)) {
7      if (!grepl("\\.", k)) {
8        normalizePath(paste0(k, ".rda"), mustWork = FALSE)
9      }
10     else {
11       normalizePath(k, mustWork = TRUE)
12     }
13   }
14   else {
15     unname(k)
16   }
17 })

With "bathy"="~/ggOceanMapsData/dd_bathy", line 7 returns TRUE (no '.' found) and line 8 is executed, mustWork=FALSE, and the program continues to asking if I want to download dd_bathy.rda
With the second path, line 7 returns FALSE ('.' found because of the "/4.2/" directory) and line 11 is executed. No file is found, but mustWork=TRUE and the program fails. It seems to me that line 7 is only looking for file extensions, not '.' characters so "mustWork" shouldn't be TRUE in this scenario.

**Comment by MikkoVihtakari** [comment]
Thanks for the report. This system is new and all possible combinations has not been tested properly. These kinds of bugs are likely. I don't have the time to test this right now. Would you have time to check how to fix the issue and suggest a solution?

Right it's line 7 which gets confused here. It is trying to look for file extension. [tools::file_ext](https://search.r-project.org/R/refmans/tools/html/fileutils.html) would be a function which could be used to solve this, but I am hesitant adding more dependencies. They tend to cause issues.

**Comment by eaalto** [comment]
You could check if there's a '.' with no '/' after it, I suppose? I'm not
that good at grep regular expressions, but another way would be to take the
substring after the last '/' character and check just that for '.'.
         -Emil

**Comment by MikkoVihtakari** [comment]
See whether this fixes the issue: https://github.com/MikkoVihtakari/ggOceanMaps/commit/e47a8d2cea972aecfd6ddb775bc922e43051eb8d

(in other words, update to the newest GitHub version and try using the file path with . in it)

**Comment by MikkoVihtakari** [comment]
I'll close this. Reopen if it didn't work.
