### ISSUE TITLE
Error in st_coordinates.sfc(clip_boundary) 

### ISSUE THREAD

**Issue by yiyuanbi** [MikkoVihtakari/ggOceanMaps#35]
Hi there, thanks for your efforts on ggOceanMaps, it's a wonderful package!

I encountered some issues while using the 'basemap' function to plot a global map recently. 
Here is the detailed information:

>library(ggOceanMaps)
>basemap(c(-180, 180, -90, 90), bathymetry = T)
Error:
Detecting antimeridian crossing with old PROJ version. Plotting might not work as intended.
Please update your PROJ to plot maps crossing the antimeridian.
Error in st_coordinates.sfc(clip_boundary) :
not implemented for objects of class sfc_GEOMETRYCOLLECTION

This code used to work well but it started failing recently, even after updating ggOceanMaps to version 2.1.6. 
Do you have any ideas about this issue?

**Comment by MikkoVihtakari** [comment]
It tells the issue in the diagnostics: your PROJ is outdated.

**Comment by MikkoVihtakari** [comment]
> It tells the issue in the diagnostics: your PROJ is outdated. This has to do with how the sf package uses s2 these days and does not assume flat earth any longer.

Actually, scratch that. I get the same error. This is probably one of those special cases where the antimeridian handling fails. There are so many special cases...Needs to be addressed at some point.

**Comment by MikkoVihtakari** [comment]
It should work now after this fix:

Note, however, that some cases crossing the antimeridian still do not work, because it is difficult to st_transform the land shape to certain coordinate and crs combinations. I turned off the automatic rotation when crossing antimeridian to make these cases more obvious. 

``` r
library(ggOceanMaps)
#> Loading required package: ggplot2
#> ggOceanMaps: Setting data download folder to a temporary folder
#> /var/folders/9v/b70pd53x04d3jjmlrbcgp4_w0000gv/T//RtmpRYNxqX. This
#> means that any downloaded map data need to be downloaded again when you
#> restart R. To avoid this problem, change the default path to a
#> permanent folder on your computer. Add following lines to your
#> .Rprofile file: {.ggOceanMapsenv <- new.env(); .ggOceanMapsenv$datapath
#> <- 'YourCustomPath'}. You can use usethis::edit_r_profile() to edit the
#> file. '~/ggOceanMapsLargeData' would make it in a writable folder on
#> most operating systems.
packageVersion("ggOceanMaps")
#> [1] '2.1.9'

basemap(c(-180, 180, -90, 90), bathymetry = TRUE)
```

![](https://i.imgur.com/ObVlseX.png)

``` r

basemap(c(-10, -160, -90, 90), rotate = TRUE)
```

![](https://i.imgur.com/NHvydVF.png)

``` r

basemap(c(-10, -160, -90, 90))
```

![](https://i.imgur.com/BVqitgu.png)

<sup>Created on 2023-11-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by yiyuanbi** [comment]
Great! Thanks!
