### ISSUE TITLE
bathy.style = "rub" not adding bathymetry to map when using GEBCO file

### ISSUE THREAD

**Issue by difontaine** [MikkoVihtakari/ggOceanMaps#38]
I am trying to make a map with high resolution bathymetry using the GEBCO_2023.nc file. I unzipped the GEBCO download in my Downloads folder

#set options
options(ggOceanMaps.userpath = "~/Downloads/gebco_2023/GEBCO_2023.nc")

#check to make sure options are set
> getOption("ggOceanMaps.userpath")
[1] "~/Downloads/gebco_2023/GEBCO_2023.nc"

#make map
basemap(limits = c(-80, -60,30, 50), bathy.style = "rub")

#map does not have bathymetry on it – just the coastline. Clearly I'm missing something! Thanks for any help.

![image](https://github.com/MikkoVihtakari/ggOceanMaps/assets/47039251/4a6c8afe-bda1-450d-889d-52528e092f96)

**Comment by difontaine** [comment]
I realized that I should have specified what versions I'm using. I re-installed ggOceanMaps from the github install, so I'm using version 2.1.13 and I still don't get the bathymetry. And the R version is 4.2.3. 

I also want to add – thank you for creating this package!

**Comment by MikkoVihtakari** [comment]
Hmm...it works in my system. Are you using Windows? Could it be the "~" in your file path? Try:

```r
file.exists(getOption("ggOceanMaps.userpath"))
```

**Comment by difontaine** [comment]
Thanks for the quick response! No, I'm using a mac. And it seems like the file exists:

> file.exists(getOption("ggOceanMaps.userpath"))
[1] TRUE

I did also try restarting R after the new ggOceanMaps github install and that didn't change the output. So strange! Maybe I'll try rebooting everything again just in case? thanks

**Comment by MikkoVihtakari** [comment]
Strange indeed. I get this:

``` r
library(ggOceanMaps)
#> Loading required package: ggplot2
#> ggOceanMaps: Setting data download folder to a temporary folder
#> /var/folders/9v/b70pd53x04d3jjmlrbcgp4_w0000gv/T//Rtmpv925jI. This
#> means that any downloaded map data need to be downloaded again when you
#> restart R. To avoid this problem, change the default path to a
#> permanent folder on your computer. Add following lines to your
#> .Rprofile file: {.ggOceanMapsenv <- new.env(); .ggOceanMapsenv$datapath
#> <- 'YourCustomPath'}. You can use usethis::edit_r_profile() to edit the
#> file. '~/ggOceanMapsLargeData' would make it in a writable folder on
#> most operating systems.
options(ggOceanMaps.userpath = "~/Downloads/gebco_2023/GEBCO_2023.nc")
basemap(limits = c(-80, -60,30, 50), bathy.style = "rub")
```

![](https://i.imgur.com/V7eHLSH.png)

<sup>Created on 2023-11-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Could you try with reprex just in case you had a typo somewhere?

**Comment by difontaine** [comment]
I tried using reprex and got an output that looked like yours actually (with bathymetry) but then I couldn't figure out how to get the output pasted to here and so I tried it again  (after re-starting R) but got this:

> library(ggOceanMaps)
> options(ggOceanMaps.userpath = "~/Downloads/gebco_2023/GEBCO_2023.nc")
> basemap(limits = c(-80, -60,30, 50), bathy.style = "rub")
> reprex()
✖ Install the styler package in order to use `style = TRUE`.
ℹ Rendering reprex...
Error in parse(text = x, keep.source = TRUE) : 
  <text>:5:7: unexpected symbol
4: 
5: First three
         ^

sorry for my cluelessness! This is my first time using reprex - I can see why you want me to try with reprex though.

**Comment by difontaine** [comment]
Nevermid -- figured out how to copy, duh – so this is the output:

``` r
library(ggOceanMaps)
#> Loading required package: ggplot2
#> ggOceanMaps: Setting data download folder to a temporary folder
#> /var/folders/hw/3m77_44925j0dvws649y30fm0000gn/T//RtmpnnpLGi. This
#> means that any downloaded map data need to be downloaded again when you
#> restart R. To avoid this problem, change the default path to a
#> permanent folder on your computer. Add following lines to your
#> .Rprofile file: {.ggOceanMapsenv <- new.env(); .ggOceanMapsenv$datapath
#> <- 'YourCustomPath'}. You can use usethis::edit_r_profile() to edit the
#> file. '~/ggOceanMapsLargeData' would make it in a writable folder on
#> most operating systems.


options(ggOceanMaps.userpath = "~/Downloads/gebco_2023/GEBCO_2023.nc")

basemap(limits = c(-80, -60,30, 50), bathy.style = "rub")
```

![](https://i.imgur.com/D9a4d0p.png)

<sup>Created on 2023-11-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by MikkoVihtakari** [comment]
Hmm...the important packages seem up to date. The last straw, what do you get from `sf::sf_extSoftVersion()`

**Comment by MikkoVihtakari** [comment]
I have PROJ 9.1, GDAL 3.5 and GEOS 3.11. If nothing else helps, you may try updating those (search on web how). You did download the NetCDF file from [here](https://www.bodc.ac.uk/data/open_download/gebco/gebco_2023/zip/), right, as instructed here: https://mikkovihtakari.github.io/ggOceanMaps/articles/new-features.html#new-bathymetry-system?

Does `basemap(limits = c(-80, -60,30, 50), bathy.style = "rcb")` work?

**Comment by MikkoVihtakari** [comment]
Except that you forgot `library(ggOceanMaps)` from `reprex::reprex()`, but good news if that works. I am sorry that I do not have better ideas at the moment. I can test on another machine later this week or the next and see whether I manage to reproduce the issue. I bet you are first who tries this feature apart from me, so a bug somewhere is well possible. Weird that it works on my machine, though.

**Comment by difontaine** [comment]
Not sure if this provides any clues but I ran 
``` r
basemap(limits = c(-80, -60,30, 50), bathy.style = "rcb") 
```

and I got the plot in the "plot pane" just fine, but then when I do reprex, I get this:
``` r
library(ggOceanMaps)
#> Loading required package: ggplot2
#> ggOceanMaps: Setting data download folder to a temporary folder
#> /var/folders/hw/3m77_44925j0dvws649y30fm0000gn/T//RtmpinwSv0. This
#> means that any downloaded map data need to be downloaded again when you
#> restart R. To avoid this problem, change the default path to a
#> permanent folder on your computer. Add following lines to your
#> .Rprofile file: {.ggOceanMapsenv <- new.env(); .ggOceanMapsenv$datapath
#> <- 'YourCustomPath'}. You can use usethis::edit_r_profile() to edit the
#> file. '~/ggOceanMapsLargeData' would make it in a writable folder on
#> most operating systems.



basemap(limits = c(-80, -60,30, 50), bathy.style = "rcb")
#> Cannot find files:
#> /var/folders/hw/3m77_44925j0dvws649y30fm0000gn/T//RtmpinwSv0/dd_rbathy_cont.rda.
#> Do you want download them now?
#> Error in utils::menu(c("Yes", "No"), ""): menu() cannot be used non-interactively
```

<sup>Created on 2023-11-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by difontaine** [comment]
Great news!!! I am a slacker on my computer and R updates. I was using an older version of R and now that it is updated, the code works perfectly and I get the expected result:
![image](https://github.com/MikkoVihtakari/ggOceanMaps/assets/47039251/15c78e24-f222-4ff9-a20c-68be411c3df4)

Thank you so much for the assistance.
