### ISSUE TITLE
Missing Svalbard_bathy.rda

### ISSUE THREAD

**Issue by Telegonus** [MikkoVihtakari/ggOceanMaps#41]
Hello,

While trying to plot some maps of the Bathymetry in isfjorden i could not get it more detailed than 0-50m, 50-300 and 300-500.
When trying to call the Svalbard_bathy.rda it seems to be missing in the ggOceanMapsLargeData. 

Has it been removed on purpose?

Cheers,
Vegard

**Comment by MikkoVihtakari** [comment]
Svalbard_bathy was made from GEBCO bathymetry, I'd recall. You can use bathy.style = "rcb" nowadays, which should have a higher resolution than the old svalbard_bathy. If that is not enough, you may also use GEBCO grid directly and bathy.style = "rub". See: https://mikkovihtakari.github.io/ggOceanMaps/articles/new-features.html
