### ISSUE TITLE
Issue CRS (auto_limits function)

### ISSUE THREAD

**Issue by yreecht** [MikkoVihtakari/ggOceanMaps#7]
Hi Mikko,

Thanks for sharing this useful package.

The default value `proj.in = "EPSG:4326"` in the function auto_limits does not work on all systems. This is because of a non-systematic support of `SRS_string` in the package sp (`projargs` is passed to `SRS_string` if in this format and sp >= 1.4-4):

> SRS_string:      default NULL, **only used when rgdal is built with PROJ >= 6 and GDAL >= 3**; a valid WKT string or SRS definition such as "EPSG:4326" or "ESRI:102761"

This is in particular an issue when building packages under some LTS Linux distributions, where it makes the function `basemap` unusable.

An easy workaround would be, I think, to use `proj.in = "+init=epsg:4326"` instead.

Best wishes,
Yves

**Comment by yreecht** [comment]
Okay, I realise that this is probably linked to the shifting to the PROJ6/GDAL3 system you mention on the front page. Sorry if the issue is irrelevant. 

Is this kind of projection specification (`"+init=epsg:XXXX"`) supposed to eventually become obsolete?

**Comment by MikkoVihtakari** [comment]
Thanks for reporting the issue. I think sf, sp, rgdal, and rgeos developers are rolling to PROJ >= 6 and GDAL >= 3, and the support for older versions will be ditched eventually. Is there any way you could update PROJ and GDAL on your system?

As a work-around, one could try to detect which version of PROJ and GDAL the system uses and adjust the argument accordingly. Please tell me, if you find a test that works. I think I have a few drafts somewhere. Need to find them. I'll do a serious attempt to make the package CRAN compatible again later this autumn. Right now I am swamped with other tasks.

**Comment by yreecht** [comment]
Hi Mikko,

Thanks for looking into it.

An idea of function that return the adequate string depending on the installed libraries:
```

CRSargs <- function(epsg = 4326)
{
    ## Minimal versions for CRS() to support SRS_string:
    minVersions <- c("GDAL" = "3.0", "PROJ" = "6.0", "sp" = "1.4-4")

    res <- sapply(names(minVersions),
                  function(i)
           {
               utils::compareVersion(rgdal::rgdal_extSoftVersion()[i],
                                     minVersions[i])
           })
    
    return(paste0(ifelse(any(res < 0), "+init=epsg:", "EPSG:"),
                  epsg))
}


```

**Comment by MikkoVihtakari** [comment]
Thanks! The only issue here is that it requires importing rgdal. I have tried to remove that dependency and replace it with sf. The sf package might be unstable on older Linux etc distributions. Not entirely sure what is the best way forward. Anyway, sf must have function to test the GDAL version too.

More about sf here: https://github.com/MikkoVihtakari/ggOceanMaps/issues/5

**Comment by yreecht** [comment]
Yes, sorry, I missed that part!

Then:
```
CRSargs <- function(epsg = 4326)
{
    ## Minimal versions for CRS() to support SRS_string:
    minVersions <- c("GDAL" = "3.0", "PROJ" = "6.0", "sp" = "1.4-4")
    
    installed <- c(sf::sf_extSoftVersion(),
                   sp = as.character(packageVersion("sp")))[names(minVersions)]

    res <- sapply(names(minVersions),
                  function(i)
           {
               utils::compareVersion(installed[i],
                                     minVersions[i])
           })
    
    return(paste0(ifelse(any(res < 0), "+init=epsg:", "EPSG:"),
                  epsg))
}
```

**Comment by MikkoVihtakari** [comment]
Thank you. I'll report back once this is incorporated.

**Comment by yreecht** [comment]
I have implemented it in my fork... I can complete the doc and send a pull request next week if you wish.

Do you have some test scripts I can try to validate that all runs smoothly?

**Comment by MikkoVihtakari** [comment]
Yes. I have automatic tests for the most common OS. Here: https://github.com/MikkoVihtakari/ggOceanMaps/blob/master/.github/workflows/R-CMD-check.yaml

**Comment by MikkoVihtakari** [comment]
This issue should be addressed here: https://github.com/MikkoVihtakari/ggOceanMaps/commit/24780292d6750d9c530f8d44dad56fefb29cc878

I'll close the issue. Please reopen if the issue prevails.
